# Generated by Django 5.0.1 on 2024-01-29 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_rename_pedido_id_lineapedido_pedido_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lineapedido',
            name='Cantidad',
        ),
        migrations.AddField(
            model_name='lineapedido',
            name='cantidad',
            field=models.IntegerField(default=1),
        ),
    ]
