# Generated by Django 4.2.7 on 2024-01-21 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_categoria_producto_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='categoria',
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
    ]
