# Generated by Django 5.0.1 on 2024-01-24 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_carrito'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallefactura',
            name='factura',
        ),
        migrations.RemoveField(
            model_name='detallefactura',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='productos',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='Carrito',
        ),
        migrations.DeleteModel(
            name='DetalleFactura',
        ),
        migrations.DeleteModel(
            name='Factura',
        ),
    ]
