# Generated by Django 5.0.1 on 2024-01-28 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_remove_detallefactura_factura_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='producto_id',
            field=models.CharField(default=1, max_length=10, unique=True),
        ),
    ]
